- name: Jumpbox aufsetzen
  hosts: jumpbox
  roles:
    - jumpbox

- name: VMs erstellen
  hosts: jumpbox
  roles:
    - role: vm
      tags: vm

- name: VMs konfigurieren
  hosts: vm
  roles:
    - role: setup
      tags: setup
