- name: Create Image Directory in /srv
  ansible.builtin.file:
    path: "{{ image_dir }}"
    state: directory
  become: true

- name: Download Debian 12 Cloud Image
  ansible.builtin.get_url:
    url: "https://cloud.debian.org/images/cloud/bookworm/daily/latest/debian-12-generic-amd64-daily.qcow2"
    dest: "{{ image_dir }}/debian-12-generic-amd64.qcow2"
    mode: "0644"
    owner: libvirt-qemu
    group: kvm
  become: true

- name: libvirt Netz definieren
  community.libvirt.virt_net:
    command: define
    name: br_nat
    xml: '{{ lookup("file", "br_nat.xml") }}'
  become: true

- name: br_nat Netz starten
  community.libvirt.virt_net:
    command: start
    name: br_nat
    autostart: true
  become: true

- name: br_nat automatisch starten
  community.libvirt.virt_net:
    name: br_nat
    autostart: true
  become: true

- name: Kubernetes VMs starten
  community.libvirt.virt_cloud_instance:
    name: "{{ item }}"
    memory: "{{ hostvars[vm].memory }}"
    vcpus: "{{ hostvars[vm].vcpus }}"
    osinfo:
      name: debian12
    base_image: "{{ image_dir }}/debian-12-generic-amd64.qcow2"
    disks:
      - path: "/var/lib/libvirt/images/{{ item }}.qcow2"
        size: 20
        format: qcow2
    networks:
      - network: br_nat
    cloud_init:
      meta_data: "{{ lookup('ansible.builtin.template', 'meta-data.yaml.j2') }}"
      user_data: "{{ lookup('ansible.builtin.template', 'user-data.yaml.j2') }}"
      network_config: "{{ lookup('ansible.builtin.template', 'network-config.yaml.j2') }}"
    wait_for_cloud_init_reboot: false
    recreate: true
    force_disk: true
  become: true
  vars:
    vm: "{{ item }}"
  loop: "{{ groups['vm'] }}"

- name: wait for VMs
  ansible.builtin.wait_for:
    host: "{{ hostvars[item].ansible_host }}"
    port: 22
    delay: 5
    timeout: 300
    state: started
  loop: "{{ groups['vm'] }}"
