- name: apt-get update
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: apt upgrade
  ansible.builtin.apt:
    name: "*"
    state: latest
  become: true

- name: apt install 
  ansible.builtin.apt:
    pkg:
    - bridge-utils
    - cpu-checker
    - libvirt-clients
    - libvirt-dev
    - libvirt-daemon
    - libvirt-daemon-system
    - virtinst
    - qemu-kvm
    - pkg-config
  become: true

- name: Download-Verzeichnis anlegen
  ansible.builtin.file:
    path: "{{ download_dir }}"
    state: directory
    mode: "0755"

- name: Download k8sTHW Binarys
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "{{ download_dir }}"
    mode: "0644"
  loop:
    - https://dl.k8s.io/v1.32.3/bin/linux/amd64/kubectl
    - https://dl.k8s.io/v1.32.3/bin/linux/amd64/kube-apiserver
    - https://dl.k8s.io/v1.32.3/bin/linux/amd64/kube-controller-manager
    - https://dl.k8s.io/v1.32.3/bin/linux/amd64/kube-scheduler
    - https://dl.k8s.io/v1.32.3/bin/linux/amd64/kube-proxy
    - https://dl.k8s.io/v1.32.3/bin/linux/amd64/kubelet
    - https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.32.0/crictl-v1.32.0-linux-amd64.tar.gz
    - https://github.com/opencontainers/runc/releases/download/v1.3.0-rc.1/runc.amd64
    - https://github.com/containernetworking/plugins/releases/download/v1.6.2/cni-plugins-linux-amd64-v1.6.2.tgz
    - https://github.com/containerd/containerd/releases/download/v2.1.0-beta.0/containerd-2.1.0-beta.0-linux-amd64.tar.gz
    - https://github.com/etcd-io/etcd/releases/download/v3.6.0-rc.3/etcd-v3.6.0-rc.3-linux-amd64.tar.gz

- name: Packages-Verzeichnis anlegen
  ansible.builtin.file:
    path: "{{ download_dir }}/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - client
    - cni-plugins
    - controller
    - worker

- name: Unarchive critcl Packages
  ansible.builtin.unarchive:
    src: "{{ download_dir}}/crictl-v1.32.0-linux-amd64.tar.gz"
    dest: "{{ download_dir}}/worker"

- name: Unarchive containerd Packages
  ansible.builtin.unarchive:
    src: "{{ download_dir}}/containerd-2.1.0-beta.0-linux-amd64.tar.gz"
    dest: "{{ download_dir}}/worker"
    extra_opts:
      - --strip-components=1

- name: Unarchive cni-plugin Packages
  ansible.builtin.unarchive:
    src: "{{ download_dir}}/cni-plugins-linux-amd64-v1.6.2.tgz"
    dest: "{{ download_dir}}/cni-plugins"

- name: Unarchive etcd Packages
  ansible.builtin.unarchive:
    src: "{{ download_dir}}/etcd-v3.6.0-rc.3-linux-amd64.tar.gz"
    dest: "{{ download_dir}}"
    extra_opts:
      - --strip-components=1

- name: Move etcdctl Ordner
  ansible.builtin.command: mv downloads/etcdctl downloads/client/

- name: Move kubectl Ordner
  ansible.builtin.command: mv downloads/kubectl downloads/client/

- name: Move etcd Ordner
  ansible.builtin.command: mv downloads/etcd downloads/controller/

- name: Move kube-apiserver Ordner
  ansible.builtin.command: mv downloads/kube-apiserver downloads/controller/

- name: Move kube-controller-manager Ordner
  ansible.builtin.command: mv downloads/kube-controller-manager downloads/controller/

- name: Move kube-scheduler Ordner
  ansible.builtin.command: mv downloads/kube-scheduler downloads/controller/

- name: Move kubelet Ordner
  ansible.builtin.command: mv downloads/kubelet downloads/worker/

- name: Move kube-proxy Ordner
  ansible.builtin.command: mv downloads/kube-proxy downloads/worker/

- name: Move runc Ordner
  ansible.builtin.command: mv downloads/runc.amd64 downloads/worker/runc

- name: Make Binarys ausführbar
  ansible.builtin.file:
    path: "{{ download_dir }}/{{ item }}"
    state: directory
    recurse: true
    mode: '0755'
  loop:
    - client
    - cni-plugins
    - controller
    - worker

- name: Kopiere Binary
  ansible.builtin.copy:
    src: "{{ download_dir }}/client/kubectl"
    dest: /usr/local/bin
    mode: '0755'
  become: true

- name: kubectl version abfragen
  ansible.builtin.command:
    cmd: "kubectl version --client -o json"
  register: kubectl_version
  changed_when: false

- name: kubectl version verifizieren
  ansible.builtin.assert:
    that:
      - (kubectl_version.stdout | from_json).clientVersion.gitVersion == k8s_version
